# Generated by Django 5.2.17 on 2026-09-12 17:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_depot_is_transfer_hub'),
        ('routing', '0002_route_safety_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_arrival', models.TimeField(help_text="Feeder route's predicted arrival at the hub.")),
                ('planned_departure', models.TimeField(help_text="Trunk route's scheduled time at the hub stop.")),
                ('buffer_minutes', models.PositiveIntegerField(default=5)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('wheelchair_count', models.PositiveIntegerField(default=0)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='districts.depot')),
                ('feeder_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='routing.route')),
                ('trunk_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='routing.route')),
            ],
            options={
                'ordering': ['planned_arrival'],
                'unique_together': {('feeder_route', 'trunk_route')},
            },
        ),
    ]
