# Generated by Django 5.2.17 on 2026-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('accident', 'Accident'), ('breakdown', 'Breakdown'), ('traffic', 'Traffic'), ('weather', 'Weather'), ('behavior', 'Student behavior'), ('medical', 'Medical'), ('other', 'Other')], max_length=20),
        ),
    ]
