# Generated by Django 5.2.17 on 2026-09-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0003_depot_is_transfer_hub'),
        ('transportation', '0002_busstop_safety_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='transfer_hub',
            field=models.ForeignKey(blank=True, help_text='If set, students at this stop ride a feeder route to this hub and transfer to a second bus for the rest of the trip, instead of riding straight to school.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeder_stops', to='districts.depot'),
        ),
    ]
