# Generated by Django 5.2.17 on 2026-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('districts', '0002_district_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='is_transfer_hub',
            field=models.BooleanField(default=False, help_text='Students from feeder-flagged stops (BusStop.transfer_hub) are dropped here and board a second bus that continues to school. See apps.routing.models.RouteTransfer.'),
        ),
    ]
